#spring.application.name=tastybuddy-backend


spring.datasource.url=jdbc:mysql://localhost:3306/tastybuddy
spring.datasource.username=root
spring.datasource.password=sAKSHI@999

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8080


#Razorpay Keys
razorpay.key=rzp_test_SZK3uWPPnUR5xh
razorpay.secret=TOvFSsgYktwjt4f26K6IiXKi